application:
  name: simple-example-node-2
  project: getting-started
  cloud_region: aws/us-west-2
  publicly_accessible: true
routers:
- name: main-2
  routes:
  - application_name: simple-example-node-2
    paths:
    - /
