application:
  name: simple-example-node-2
  organization: QoveryCommunity
  project: getting-started
  publicly_accessible: true
routers:
- name: main-2
  routes:
  - application_name: simple-example-node-2
    paths:
    - /
